server:
  port: 8085

spring:
  application:
    name: notification-service
  config:
    import: "optional:nacos:${spring.application.name}.yaml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/expense_flow?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 20
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

dingtalk:
  mock: false
  webhook-url: https://oapi.dingtalk.com/robot/send?access_token=d00acc979da8c7cc32ebe229dae7743540df6043e77d7149ebc33d9e53093c1f

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
