global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'expenseflow-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'gateway-service:8080'
          - 'system-service:8081'
          - 'expense-service:8082'
          - 'approval-service:8083'
          - 'ai-service:8084'
          - 'notification-service:8085'
